import { useState, useEffect } from "react";
import Confetti from "react-confetti";
import { CircularProgressbar, buildStyles } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";

import Sidebar from "../components/Sidebar";
import syllabus from "../data/syllabus";
import "../styles/dashboard.css";
import { generateQuiz } from "../services/quizService";

export default function Quiz() {
  const [board, setBoard] = useState("CBSE");
  const [studentClass, setStudentClass] = useState("10");
  const [subject, setSubject] = useState("Science");
  const [chapter, setChapter] = useState("");

  const [quiz, setQuiz] = useState([]);
  const [answers, setAnswers] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);

  const [currentQuestion, setCurrentQuestion] = useState(0);

  // 10 minute timer
  const QUIZ_DURATION = 600;
  const [timeLeft, setTimeLeft] = useState(QUIZ_DURATION);

  const chapters =
    syllabus?.[board]?.[studentClass]?.[subject] || [];

  useEffect(() => {
    if (!quiz.length || submitted) return;

    const timer = setInterval(() => {
      setTimeLeft((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          setSubmitted(true);
          return 0;
        }

        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);

  }, [quiz, submitted]);

  async function handleGenerate() {

    if (!chapter) {
      alert("Please select a chapter.");
      return;
    }

    setLoading(true);

    try {

      const result = await generateQuiz(
        board,
        studentClass,
        subject,
        chapter
      );

      setQuiz(result);
      setAnswers({});
      setSubmitted(false);
      setCurrentQuestion(0);
      setTimeLeft(QUIZ_DURATION);

    } catch (error) {

      alert(error.message);

    } finally {

      setLoading(false);

    }
  }

  function handleOptionChange(option) {

    setAnswers((prev) => ({
      ...prev,
      [currentQuestion]: option,
    }));

  }

  function nextQuestion() {

    if (currentQuestion < quiz.length - 1) {
      setCurrentQuestion((prev) => prev + 1);
    }

  }

  function previousQuestion() {

    if (currentQuestion > 0) {
      setCurrentQuestion((prev) => prev - 1);
    }

  }

  function calculateScore() {

    let score = 0;

    quiz.forEach((q, index) => {

      if (answers[index] === q.answer) {
        score++;
      }

    });

    return score;
  }

  function resetQuiz() {

    setAnswers({});
    setSubmitted(false);
    setCurrentQuestion(0);
    setTimeLeft(QUIZ_DURATION);

  }

  const progress =
    quiz.length > 0
      ? ((currentQuestion + 1) / quiz.length) * 100
      : 0;

  const current = quiz[currentQuestion];

  const finalScore = calculateScore();

  const minutesTaken = Math.floor((QUIZ_DURATION - timeLeft) / 60);
  const secondsTaken = (QUIZ_DURATION - timeLeft) % 60;

  let badge = "";
  let badgeColor = "";

  if (finalScore >= 9) {
    badge = "🥇 Gold";
    badgeColor = "#FFD700";
  } else if (finalScore >= 7) {
    badge = "🥈 Silver";
    badgeColor = "#C0C0C0";
  } else if (finalScore >= 5) {
    badge = "🥉 Bronze";
    badgeColor = "#CD7F32";
  } else {
    badge = "📚 Keep Practicing";
    badgeColor = "#888";
  }

  return (
        <div className="dashboard">

      <Sidebar />

      <main className="dashboard-content">

        <h1>❓ AI Quiz Generator</h1>

        <p className="dashboard-subtitle">
          Practice board-level quizzes generated by AI.
        </p>

        <label>Board</label>

        <select
          className="note-select"
          value={board}
          onChange={(e) => {
            setBoard(e.target.value);
            setChapter("");
          }}
        >
          <option>CBSE</option>
          <option>ICSE</option>
          <option>State Board</option>
          <option>JEE</option>
          <option>NEET</option>
          <option>Engineering</option>
        </select>

        <br /><br />

        <label>Class</label>

        <select
          className="note-select"
          value={studentClass}
          onChange={(e) => {
            setStudentClass(e.target.value);
            setChapter("");
          }}
        >
          <option>6</option>
          <option>7</option>
          <option>8</option>
          <option>9</option>
          <option>10</option>
          <option>11</option>
          <option>12</option>
        </select>

        <br /><br />

        <label>Subject</label>

        <select
          className="note-select"
          value={subject}
          onChange={(e) => {
            setSubject(e.target.value);
            setChapter("");
          }}
        >
          <option>Science</option>
          <option>Mathematics</option>
          <option>Social Science</option>
          <option>English</option>
        </select>

        <br /><br />

        <label>Chapter</label>

        <select
          className="note-select"
          value={chapter}
          onChange={(e) => setChapter(e.target.value)}
        >
          <option value="">Select Chapter</option>

          {chapters.map((item) => (
            <option key={item} value={item}>
              {item}
            </option>
          ))}
        </select>

        <br /><br />

        <button
          className="generate-btn"
          onClick={handleGenerate}
          disabled={loading}
        >
          {loading
            ? "Generating Quiz..."
            : "❓ Generate Quiz"}
        </button>

        <br /><br />

        {quiz.length > 0 && !submitted && (

          <>

            <div className="flashcard">

              <div
                style={{
                  textAlign: "right",
                  color: "#ff5722",
                  fontWeight: "bold",
                  marginBottom: "15px",
                  fontSize: "18px",
                }}
              >
                ⏱ {Math.floor(timeLeft / 60)}:
                {(timeLeft % 60).toString().padStart(2, "0")}
              </div>

              <h2>
                Question {currentQuestion + 1} of {quiz.length}
              </h2>

              <div className="progress-container">
                <div
                  className="progress-fill"
                  style={{
                    width: `${progress}%`,
                  }}
                />
              </div>

              <br />

              <h3>{current.question}</h3>

              <br />

              {current.options.map((option) => {

                const isSelected =
                  answers[currentQuestion] === option;

                return (

                  <label
                    key={option}
                    style={{
                      display: "block",
                      padding: "15px",
                      marginBottom: "12px",
                      borderRadius: "10px",
                      cursor: "pointer",
                    }}
                  >

                    <input
                      type="radio"
                      name={`question-${currentQuestion}`}
                      checked={isSelected}
                      onChange={() =>
                        handleOptionChange(option)
                      }
                    />

                    {" "}
                    {option}

                  </label>

                );

              })}

            </div>

            <br />

            <div className="study-navigation">

              <button
                className="study-btn"
                onClick={previousQuestion}
                disabled={currentQuestion === 0}
              >
                ⬅ Previous
              </button>

              {currentQuestion === quiz.length - 1 ? (

                <button
                  className="generate-btn"
                  disabled={
                    answers[currentQuestion] === undefined
                  }
                  onClick={() => setSubmitted(true)}
                >
                  ✅ Submit Quiz
                </button>

              ) : (

                <button
                  className="study-btn"
                  disabled={
                    answers[currentQuestion] === undefined
                  }
                  onClick={nextQuestion}
                >
                  Next ➡
                </button>

              )}

            </div>

          </>

        )}

        {submitted && (
                    <>
            {finalScore >= 9 && (
              <Confetti
                recycle={false}
                numberOfPieces={300}
              />
            )}

            <div className="notes-box">

              <h2>🎉 Quiz Completed!</h2>

              <div
                style={{
                  width: "180px",
                  margin: "25px auto",
                }}
              >
                <CircularProgressbar
                  value={(finalScore / quiz.length) * 100}
                  text={`${Math.round(
                    (finalScore / quiz.length) * 100
                  )}%`}
                  styles={buildStyles({
                    textSize: "16px",
                    pathColor: "#4CAF50",
                    textColor: "#222",
                    trailColor: "#ddd",
                  })}
                />
              </div>

              <h2 style={{ textAlign: "center" }}>
                Score: {finalScore} / {quiz.length}
              </h2>

              <div
                style={{
                  textAlign: "center",
                  marginTop: "20px",
                }}
              >
                <h2
                  style={{
                    color: badgeColor,
                    fontSize: "34px",
                  }}
                >
                  {badge}
                </h2>

                <p>Achievement Unlocked!</p>
              </div>

              <hr style={{ margin: "25px 0" }} />

              <h2 style={{ textAlign: "center" }}>
                📊 Performance Analytics
              </h2>

              <div className="analytics-grid">

                <div className="analytics-card">
                  <h3>🟢 Correct</h3>
                  <p>{finalScore}</p>
                </div>

                <div className="analytics-card">
                  <h3>🔴 Wrong</h3>
                  <p>{quiz.length - finalScore}</p>
                </div>

                <div className="analytics-card">
                  <h3>🎯 Accuracy</h3>
                  <p>
                    {Math.round(
                      (finalScore / quiz.length) * 100
                    )}
                    %
                  </p>
                </div>

                <div className="analytics-card">
                  <h3>⏱ Time Taken</h3>
                  <p>
                    {minutesTaken}m {secondsTaken}s
                  </p>
                </div>

              </div>

              <br />

              <button
                className="generate-btn"
                onClick={resetQuiz}
              >
                🔄 Try Again
              </button>

              <button
                className="copy-btn"
                onClick={handleGenerate}
                style={{ marginLeft: "10px" }}
              >
                ✨ Generate New Quiz
              </button>

            </div>

          </>
        )}

      </main>

    </div>
  );
}